/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 18 04:52:55 GMT 2017
 */

package introclass.median;

import org.junit.Test;
import static org.junit.Assert.*;
import introclass.median.mid;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class mid_ESTest extends mid_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 70 covered goals:
   * Goal 1. introclass.median.mid.<init>()V: root-Branch
   * Goal 2. introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true
   * Goal 3. introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false
   * Goal 4. introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - false
   * Goal 5. introclass.median.mid.median(III)I: I58 Branch 8 IF_ICMPLE L45 - true
   * Goal 6. introclass.median.mid.median(III)I: I68 Branch 9 IF_ICMPGT L47 - false
   * Goal 7. Branch introclass.median.mid.<init>()V: root-Branch in context: introclass.median.mid:<init>()V
   * Goal 8. Branch introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true in context: introclass.median.mid:median(III)I
   * Goal 9. Branch introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false in context: introclass.median.mid:median(III)I
   * Goal 10. Branch introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - false in context: introclass.median.mid:median(III)I
   * Goal 11. Branch introclass.median.mid.median(III)I: I58 Branch 8 IF_ICMPLE L45 - true in context: introclass.median.mid:median(III)I
   * Goal 12. Branch introclass.median.mid.median(III)I: I68 Branch 9 IF_ICMPGT L47 - false in context: introclass.median.mid:median(III)I
   * Goal 13. [Output]: introclass.median.mid.median(III)I:Zero
   * Goal 14. introclass.median.mid.<init>()V: Line 6
   * Goal 15. introclass.median.mid.median(III)I: Line 20
   * Goal 16. introclass.median.mid.median(III)I: Line 33
   * Goal 17. introclass.median.mid.median(III)I: Line 43
   * Goal 18. introclass.median.mid.median(III)I: Line 44
   * Goal 19. introclass.median.mid.median(III)I: Line 45
   * Goal 20. introclass.median.mid.median(III)I: Line 47
   * Goal 21. introclass.median.mid.median(III)I: Line 48
   * Goal 22. introclass.median.mid.median(III)I: Line 54
   * Goal 23. [METHOD] introclass.median.mid.<init>()V
   * Goal 24. [METHOD] introclass.median.mid.median(III)I
   * Goal 25. [METHODNOEX] introclass.median.mid.<init>()V
   * Goal 26. [METHODNOEX] introclass.median.mid.median(III)I
   * Goal 27. Weak Mutation 0: introclass.median.mid.median(III)I:20 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 1: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC 1
   * Goal 29. Weak Mutation 2: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC -1
   * Goal 30. Weak Mutation 3: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 4: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 32. Weak Mutation 5: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 33. Weak Mutation 6: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 34. Weak Mutation 7: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 35. Weak Mutation 8: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 36. Weak Mutation 11: introclass.median.mid.median(III)I:33 - ReplaceComparisonOperator <= -> ==
   * Goal 37. Weak Mutation 57: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 58: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 39. Weak Mutation 59: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 40. Weak Mutation 60: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 41. Weak Mutation 61: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 42. Weak Mutation 62: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 43. Weak Mutation 63: introclass.median.mid.median(III)I:43 - ReplaceComparisonOperator > -> !=
   * Goal 44. Weak Mutation 66: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 45. Weak Mutation 67: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 46. Weak Mutation 68: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 47. Weak Mutation 69: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 48. Weak Mutation 70: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 49. Weak Mutation 71: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 50. Weak Mutation 72: introclass.median.mid.median(III)I:44 - ReplaceComparisonOperator <= -> -1
   * Goal 51. Weak Mutation 75: introclass.median.mid.median(III)I:45 - InsertUnaryOp Negation
   * Goal 52. Weak Mutation 76: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC 1
   * Goal 53. Weak Mutation 77: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC -1
   * Goal 54. Weak Mutation 78: introclass.median.mid.median(III)I:45 - InsertUnaryOp Negation
   * Goal 55. Weak Mutation 79: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC 1
   * Goal 56. Weak Mutation 80: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC -1
   * Goal 57. Weak Mutation 82: introclass.median.mid.median(III)I:45 - ReplaceComparisonOperator <= -> <
   * Goal 58. Weak Mutation 87: introclass.median.mid.median(III)I:47 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 88: introclass.median.mid.median(III)I:47 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 89: introclass.median.mid.median(III)I:47 - InsertUnaryOp IINC -1
   * Goal 61. Weak Mutation 90: introclass.median.mid.median(III)I:47 - InsertUnaryOp Negation
   * Goal 62. Weak Mutation 91: introclass.median.mid.median(III)I:47 - InsertUnaryOp IINC 1
   * Goal 63. Weak Mutation 92: introclass.median.mid.median(III)I:47 - InsertUnaryOp IINC -1
   * Goal 64. Weak Mutation 95: introclass.median.mid.median(III)I:47 - ReplaceComparisonOperator > -> >=
   * Goal 65. Weak Mutation 96: introclass.median.mid.median(III)I:48 - InsertUnaryOp Negation
   * Goal 66. Weak Mutation 97: introclass.median.mid.median(III)I:48 - InsertUnaryOp IINC 1
   * Goal 67. Weak Mutation 98: introclass.median.mid.median(III)I:48 - InsertUnaryOp IINC -1
   * Goal 68. Weak Mutation 111: introclass.median.mid.median(III)I:54 - InsertUnaryOp Negation
   * Goal 69. Weak Mutation 112: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC 1
   * Goal 70. Weak Mutation 113: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC -1
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      mid mid0 = new mid();
      int int0 = mid0.median(0, 699, 0);
      assertEquals(0, int0);
  }

  //Test case number: 1
  /*
   * 60 covered goals:
   * Goal 1. introclass.median.mid.<init>()V: root-Branch
   * Goal 2. introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true
   * Goal 3. introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false
   * Goal 4. introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - true
   * Goal 5. introclass.median.mid.median(III)I: I78 Branch 10 IF_ICMPGT L50 - false
   * Goal 6. Branch introclass.median.mid.<init>()V: root-Branch in context: introclass.median.mid:<init>()V
   * Goal 7. Branch introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true in context: introclass.median.mid:median(III)I
   * Goal 8. Branch introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false in context: introclass.median.mid:median(III)I
   * Goal 9. Branch introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - true in context: introclass.median.mid:median(III)I
   * Goal 10. Branch introclass.median.mid.median(III)I: I78 Branch 10 IF_ICMPGT L50 - false in context: introclass.median.mid:median(III)I
   * Goal 11. [Output]: introclass.median.mid.median(III)I:Zero
   * Goal 12. introclass.median.mid.<init>()V: Line 6
   * Goal 13. introclass.median.mid.median(III)I: Line 20
   * Goal 14. introclass.median.mid.median(III)I: Line 33
   * Goal 15. introclass.median.mid.median(III)I: Line 43
   * Goal 16. introclass.median.mid.median(III)I: Line 44
   * Goal 17. introclass.median.mid.median(III)I: Line 50
   * Goal 18. introclass.median.mid.median(III)I: Line 51
   * Goal 19. introclass.median.mid.median(III)I: Line 54
   * Goal 20. [METHOD] introclass.median.mid.<init>()V
   * Goal 21. [METHOD] introclass.median.mid.median(III)I
   * Goal 22. [METHODNOEX] introclass.median.mid.<init>()V
   * Goal 23. [METHODNOEX] introclass.median.mid.median(III)I
   * Goal 24. Weak Mutation 0: introclass.median.mid.median(III)I:20 - InsertUnaryOp Negation
   * Goal 25. Weak Mutation 1: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC 1
   * Goal 26. Weak Mutation 2: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC -1
   * Goal 27. Weak Mutation 3: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 4: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 29. Weak Mutation 5: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 30. Weak Mutation 6: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 7: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 32. Weak Mutation 8: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 33. Weak Mutation 10: introclass.median.mid.median(III)I:33 - ReplaceComparisonOperator <= -> <
   * Goal 34. Weak Mutation 57: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 35. Weak Mutation 58: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 36. Weak Mutation 59: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 37. Weak Mutation 60: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 61: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 39. Weak Mutation 62: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 40. Weak Mutation 65: introclass.median.mid.median(III)I:43 - ReplaceComparisonOperator > -> >=
   * Goal 41. Weak Mutation 66: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 42. Weak Mutation 67: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 43. Weak Mutation 68: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 44. Weak Mutation 69: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 45. Weak Mutation 70: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 46. Weak Mutation 71: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 47. Weak Mutation 74: introclass.median.mid.median(III)I:44 - ReplaceComparisonOperator <= -> ==
   * Goal 48. Weak Mutation 99: introclass.median.mid.median(III)I:50 - InsertUnaryOp Negation
   * Goal 49. Weak Mutation 100: introclass.median.mid.median(III)I:50 - InsertUnaryOp IINC 1
   * Goal 50. Weak Mutation 101: introclass.median.mid.median(III)I:50 - InsertUnaryOp IINC -1
   * Goal 51. Weak Mutation 102: introclass.median.mid.median(III)I:50 - InsertUnaryOp Negation
   * Goal 52. Weak Mutation 103: introclass.median.mid.median(III)I:50 - InsertUnaryOp IINC 1
   * Goal 53. Weak Mutation 104: introclass.median.mid.median(III)I:50 - InsertUnaryOp IINC -1
   * Goal 54. Weak Mutation 105: introclass.median.mid.median(III)I:50 - ReplaceComparisonOperator > -> !=
   * Goal 55. Weak Mutation 108: introclass.median.mid.median(III)I:51 - InsertUnaryOp Negation
   * Goal 56. Weak Mutation 109: introclass.median.mid.median(III)I:51 - InsertUnaryOp IINC 1
   * Goal 57. Weak Mutation 110: introclass.median.mid.median(III)I:51 - InsertUnaryOp IINC -1
   * Goal 58. Weak Mutation 111: introclass.median.mid.median(III)I:54 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 112: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 113: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC -1
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      mid mid0 = new mid();
      int int0 = mid0.median(0, 0, 699);
      assertEquals(0, int0);
  }

  //Test case number: 2
  /*
   * 70 covered goals:
   * Goal 1. introclass.median.mid.<init>()V: root-Branch
   * Goal 2. introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - false
   * Goal 3. introclass.median.mid.median(III)I: I13 Branch 2 IF_ICMPLE L34 - true
   * Goal 4. introclass.median.mid.median(III)I: I23 Branch 3 IF_ICMPGT L36 - false
   * Goal 5. introclass.median.mid.median(III)I: I28 Branch 4 IF_ICMPLE L37 - true
   * Goal 6. introclass.median.mid.median(III)I: I38 Branch 5 IF_ICMPGT L39 - false
   * Goal 7. Branch introclass.median.mid.<init>()V: root-Branch in context: introclass.median.mid:<init>()V
   * Goal 8. Branch introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - false in context: introclass.median.mid:median(III)I
   * Goal 9. Branch introclass.median.mid.median(III)I: I13 Branch 2 IF_ICMPLE L34 - true in context: introclass.median.mid:median(III)I
   * Goal 10. Branch introclass.median.mid.median(III)I: I23 Branch 3 IF_ICMPGT L36 - false in context: introclass.median.mid:median(III)I
   * Goal 11. Branch introclass.median.mid.median(III)I: I28 Branch 4 IF_ICMPLE L37 - true in context: introclass.median.mid:median(III)I
   * Goal 12. Branch introclass.median.mid.median(III)I: I38 Branch 5 IF_ICMPGT L39 - false in context: introclass.median.mid:median(III)I
   * Goal 13. [Output]: introclass.median.mid.median(III)I:Positive
   * Goal 14. introclass.median.mid.<init>()V: Line 6
   * Goal 15. introclass.median.mid.median(III)I: Line 20
   * Goal 16. introclass.median.mid.median(III)I: Line 33
   * Goal 17. introclass.median.mid.median(III)I: Line 34
   * Goal 18. introclass.median.mid.median(III)I: Line 36
   * Goal 19. introclass.median.mid.median(III)I: Line 37
   * Goal 20. introclass.median.mid.median(III)I: Line 39
   * Goal 21. introclass.median.mid.median(III)I: Line 40
   * Goal 22. introclass.median.mid.median(III)I: Line 54
   * Goal 23. [METHOD] introclass.median.mid.<init>()V
   * Goal 24. [METHOD] introclass.median.mid.median(III)I
   * Goal 25. [METHODNOEX] introclass.median.mid.<init>()V
   * Goal 26. [METHODNOEX] introclass.median.mid.median(III)I
   * Goal 27. Weak Mutation 0: introclass.median.mid.median(III)I:20 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 1: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC 1
   * Goal 29. Weak Mutation 2: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC -1
   * Goal 30. Weak Mutation 3: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 4: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 32. Weak Mutation 5: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 33. Weak Mutation 6: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 34. Weak Mutation 7: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 35. Weak Mutation 8: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 36. Weak Mutation 9: introclass.median.mid.median(III)I:33 - ReplaceComparisonOperator <= -> -1
   * Goal 37. Weak Mutation 12: introclass.median.mid.median(III)I:34 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 13: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC 1
   * Goal 39. Weak Mutation 14: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC -1
   * Goal 40. Weak Mutation 15: introclass.median.mid.median(III)I:34 - InsertUnaryOp Negation
   * Goal 41. Weak Mutation 16: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC 1
   * Goal 42. Weak Mutation 17: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC -1
   * Goal 43. Weak Mutation 20: introclass.median.mid.median(III)I:34 - ReplaceComparisonOperator <= -> ==
   * Goal 44. Weak Mutation 24: introclass.median.mid.median(III)I:36 - InsertUnaryOp Negation
   * Goal 45. Weak Mutation 25: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC 1
   * Goal 46. Weak Mutation 26: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC -1
   * Goal 47. Weak Mutation 27: introclass.median.mid.median(III)I:36 - InsertUnaryOp Negation
   * Goal 48. Weak Mutation 28: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC 1
   * Goal 49. Weak Mutation 29: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC -1
   * Goal 50. Weak Mutation 30: introclass.median.mid.median(III)I:36 - ReplaceComparisonOperator > -> !=
   * Goal 51. Weak Mutation 33: introclass.median.mid.median(III)I:37 - InsertUnaryOp Negation
   * Goal 52. Weak Mutation 34: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC 1
   * Goal 53. Weak Mutation 35: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC -1
   * Goal 54. Weak Mutation 36: introclass.median.mid.median(III)I:37 - InsertUnaryOp Negation
   * Goal 55. Weak Mutation 37: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC 1
   * Goal 56. Weak Mutation 38: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC -1
   * Goal 57. Weak Mutation 41: introclass.median.mid.median(III)I:37 - ReplaceComparisonOperator <= -> ==
   * Goal 58. Weak Mutation 45: introclass.median.mid.median(III)I:39 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 46: introclass.median.mid.median(III)I:39 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 47: introclass.median.mid.median(III)I:39 - InsertUnaryOp IINC -1
   * Goal 61. Weak Mutation 48: introclass.median.mid.median(III)I:39 - InsertUnaryOp Negation
   * Goal 62. Weak Mutation 49: introclass.median.mid.median(III)I:39 - InsertUnaryOp IINC 1
   * Goal 63. Weak Mutation 50: introclass.median.mid.median(III)I:39 - InsertUnaryOp IINC -1
   * Goal 64. Weak Mutation 51: introclass.median.mid.median(III)I:39 - ReplaceComparisonOperator > -> !=
   * Goal 65. Weak Mutation 54: introclass.median.mid.median(III)I:40 - InsertUnaryOp Negation
   * Goal 66. Weak Mutation 55: introclass.median.mid.median(III)I:40 - InsertUnaryOp IINC 1
   * Goal 67. Weak Mutation 56: introclass.median.mid.median(III)I:40 - InsertUnaryOp IINC -1
   * Goal 68. Weak Mutation 111: introclass.median.mid.median(III)I:54 - InsertUnaryOp Negation
   * Goal 69. Weak Mutation 112: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC 1
   * Goal 70. Weak Mutation 113: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC -1
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      mid mid0 = new mid();
      int int0 = mid0.median(1, (-646), 812);
      assertEquals(1, int0);
  }

  //Test case number: 3
  /*
   * 60 covered goals:
   * Goal 1. introclass.median.mid.<init>()V: root-Branch
   * Goal 2. introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true
   * Goal 3. introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false
   * Goal 4. introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - false
   * Goal 5. introclass.median.mid.median(III)I: I58 Branch 8 IF_ICMPLE L45 - false
   * Goal 6. Branch introclass.median.mid.<init>()V: root-Branch in context: introclass.median.mid:<init>()V
   * Goal 7. Branch introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true in context: introclass.median.mid:median(III)I
   * Goal 8. Branch introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false in context: introclass.median.mid:median(III)I
   * Goal 9. Branch introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - false in context: introclass.median.mid:median(III)I
   * Goal 10. Branch introclass.median.mid.median(III)I: I58 Branch 8 IF_ICMPLE L45 - false in context: introclass.median.mid:median(III)I
   * Goal 11. [Output]: introclass.median.mid.median(III)I:Positive
   * Goal 12. introclass.median.mid.<init>()V: Line 6
   * Goal 13. introclass.median.mid.median(III)I: Line 20
   * Goal 14. introclass.median.mid.median(III)I: Line 33
   * Goal 15. introclass.median.mid.median(III)I: Line 43
   * Goal 16. introclass.median.mid.median(III)I: Line 44
   * Goal 17. introclass.median.mid.median(III)I: Line 45
   * Goal 18. introclass.median.mid.median(III)I: Line 46
   * Goal 19. introclass.median.mid.median(III)I: Line 54
   * Goal 20. [METHOD] introclass.median.mid.<init>()V
   * Goal 21. [METHOD] introclass.median.mid.median(III)I
   * Goal 22. [METHODNOEX] introclass.median.mid.<init>()V
   * Goal 23. [METHODNOEX] introclass.median.mid.median(III)I
   * Goal 24. Weak Mutation 0: introclass.median.mid.median(III)I:20 - InsertUnaryOp Negation
   * Goal 25. Weak Mutation 1: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC 1
   * Goal 26. Weak Mutation 2: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC -1
   * Goal 27. Weak Mutation 3: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 4: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 29. Weak Mutation 5: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 30. Weak Mutation 6: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 7: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 32. Weak Mutation 8: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 33. Weak Mutation 10: introclass.median.mid.median(III)I:33 - ReplaceComparisonOperator <= -> <
   * Goal 34. Weak Mutation 57: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 35. Weak Mutation 58: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 36. Weak Mutation 59: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 37. Weak Mutation 60: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 61: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 39. Weak Mutation 62: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 40. Weak Mutation 65: introclass.median.mid.median(III)I:43 - ReplaceComparisonOperator > -> >=
   * Goal 41. Weak Mutation 66: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 42. Weak Mutation 67: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 43. Weak Mutation 68: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 44. Weak Mutation 69: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 45. Weak Mutation 70: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 46. Weak Mutation 71: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 47. Weak Mutation 72: introclass.median.mid.median(III)I:44 - ReplaceComparisonOperator <= -> -1
   * Goal 48. Weak Mutation 75: introclass.median.mid.median(III)I:45 - InsertUnaryOp Negation
   * Goal 49. Weak Mutation 76: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC 1
   * Goal 50. Weak Mutation 77: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC -1
   * Goal 51. Weak Mutation 78: introclass.median.mid.median(III)I:45 - InsertUnaryOp Negation
   * Goal 52. Weak Mutation 79: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC 1
   * Goal 53. Weak Mutation 80: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC -1
   * Goal 54. Weak Mutation 81: introclass.median.mid.median(III)I:45 - ReplaceComparisonOperator <= -> -1
   * Goal 55. Weak Mutation 84: introclass.median.mid.median(III)I:46 - InsertUnaryOp Negation
   * Goal 56. Weak Mutation 85: introclass.median.mid.median(III)I:46 - InsertUnaryOp IINC 1
   * Goal 57. Weak Mutation 86: introclass.median.mid.median(III)I:46 - InsertUnaryOp IINC -1
   * Goal 58. Weak Mutation 111: introclass.median.mid.median(III)I:54 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 112: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 113: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC -1
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      mid mid0 = new mid();
      int int0 = mid0.median(699, 699, 0);
      assertEquals(699, int0);
  }

  //Test case number: 4
  /*
   * 60 covered goals:
   * Goal 1. introclass.median.mid.<init>()V: root-Branch
   * Goal 2. introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true
   * Goal 3. introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false
   * Goal 4. introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - true
   * Goal 5. introclass.median.mid.median(III)I: I78 Branch 10 IF_ICMPGT L50 - false
   * Goal 6. Branch introclass.median.mid.<init>()V: root-Branch in context: introclass.median.mid:<init>()V
   * Goal 7. Branch introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true in context: introclass.median.mid:median(III)I
   * Goal 8. Branch introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false in context: introclass.median.mid:median(III)I
   * Goal 9. Branch introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - true in context: introclass.median.mid:median(III)I
   * Goal 10. Branch introclass.median.mid.median(III)I: I78 Branch 10 IF_ICMPGT L50 - false in context: introclass.median.mid:median(III)I
   * Goal 11. [Output]: introclass.median.mid.median(III)I:Positive
   * Goal 12. introclass.median.mid.<init>()V: Line 6
   * Goal 13. introclass.median.mid.median(III)I: Line 20
   * Goal 14. introclass.median.mid.median(III)I: Line 33
   * Goal 15. introclass.median.mid.median(III)I: Line 43
   * Goal 16. introclass.median.mid.median(III)I: Line 44
   * Goal 17. introclass.median.mid.median(III)I: Line 50
   * Goal 18. introclass.median.mid.median(III)I: Line 51
   * Goal 19. introclass.median.mid.median(III)I: Line 54
   * Goal 20. [METHOD] introclass.median.mid.<init>()V
   * Goal 21. [METHOD] introclass.median.mid.median(III)I
   * Goal 22. [METHODNOEX] introclass.median.mid.<init>()V
   * Goal 23. [METHODNOEX] introclass.median.mid.median(III)I
   * Goal 24. Weak Mutation 0: introclass.median.mid.median(III)I:20 - InsertUnaryOp Negation
   * Goal 25. Weak Mutation 1: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC 1
   * Goal 26. Weak Mutation 2: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC -1
   * Goal 27. Weak Mutation 3: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 4: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 29. Weak Mutation 5: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 30. Weak Mutation 6: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 7: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 32. Weak Mutation 8: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 33. Weak Mutation 10: introclass.median.mid.median(III)I:33 - ReplaceComparisonOperator <= -> <
   * Goal 34. Weak Mutation 57: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 35. Weak Mutation 58: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 36. Weak Mutation 59: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 37. Weak Mutation 60: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 61: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 39. Weak Mutation 62: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 40. Weak Mutation 65: introclass.median.mid.median(III)I:43 - ReplaceComparisonOperator > -> >=
   * Goal 41. Weak Mutation 66: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 42. Weak Mutation 67: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 43. Weak Mutation 68: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 44. Weak Mutation 69: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 45. Weak Mutation 70: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 46. Weak Mutation 71: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 47. Weak Mutation 73: introclass.median.mid.median(III)I:44 - ReplaceComparisonOperator <= -> <
   * Goal 48. Weak Mutation 99: introclass.median.mid.median(III)I:50 - InsertUnaryOp Negation
   * Goal 49. Weak Mutation 100: introclass.median.mid.median(III)I:50 - InsertUnaryOp IINC 1
   * Goal 50. Weak Mutation 101: introclass.median.mid.median(III)I:50 - InsertUnaryOp IINC -1
   * Goal 51. Weak Mutation 102: introclass.median.mid.median(III)I:50 - InsertUnaryOp Negation
   * Goal 52. Weak Mutation 103: introclass.median.mid.median(III)I:50 - InsertUnaryOp IINC 1
   * Goal 53. Weak Mutation 104: introclass.median.mid.median(III)I:50 - InsertUnaryOp IINC -1
   * Goal 54. Weak Mutation 107: introclass.median.mid.median(III)I:50 - ReplaceComparisonOperator > -> >=
   * Goal 55. Weak Mutation 108: introclass.median.mid.median(III)I:51 - InsertUnaryOp Negation
   * Goal 56. Weak Mutation 109: introclass.median.mid.median(III)I:51 - InsertUnaryOp IINC 1
   * Goal 57. Weak Mutation 110: introclass.median.mid.median(III)I:51 - InsertUnaryOp IINC -1
   * Goal 58. Weak Mutation 111: introclass.median.mid.median(III)I:54 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 112: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 113: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC -1
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      mid mid0 = new mid();
      int int0 = mid0.median(699, 699, 699);
      assertEquals(699, int0);
  }

  //Test case number: 5
  /*
   * 70 covered goals:
   * Goal 1. introclass.median.mid.<init>()V: root-Branch
   * Goal 2. introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - false
   * Goal 3. introclass.median.mid.median(III)I: I13 Branch 2 IF_ICMPLE L34 - true
   * Goal 4. introclass.median.mid.median(III)I: I23 Branch 3 IF_ICMPGT L36 - false
   * Goal 5. introclass.median.mid.median(III)I: I28 Branch 4 IF_ICMPLE L37 - true
   * Goal 6. introclass.median.mid.median(III)I: I38 Branch 5 IF_ICMPGT L39 - false
   * Goal 7. Branch introclass.median.mid.<init>()V: root-Branch in context: introclass.median.mid:<init>()V
   * Goal 8. Branch introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - false in context: introclass.median.mid:median(III)I
   * Goal 9. Branch introclass.median.mid.median(III)I: I13 Branch 2 IF_ICMPLE L34 - true in context: introclass.median.mid:median(III)I
   * Goal 10. Branch introclass.median.mid.median(III)I: I23 Branch 3 IF_ICMPGT L36 - false in context: introclass.median.mid:median(III)I
   * Goal 11. Branch introclass.median.mid.median(III)I: I28 Branch 4 IF_ICMPLE L37 - true in context: introclass.median.mid:median(III)I
   * Goal 12. Branch introclass.median.mid.median(III)I: I38 Branch 5 IF_ICMPGT L39 - false in context: introclass.median.mid:median(III)I
   * Goal 13. [Output]: introclass.median.mid.median(III)I:Positive
   * Goal 14. introclass.median.mid.<init>()V: Line 6
   * Goal 15. introclass.median.mid.median(III)I: Line 20
   * Goal 16. introclass.median.mid.median(III)I: Line 33
   * Goal 17. introclass.median.mid.median(III)I: Line 34
   * Goal 18. introclass.median.mid.median(III)I: Line 36
   * Goal 19. introclass.median.mid.median(III)I: Line 37
   * Goal 20. introclass.median.mid.median(III)I: Line 39
   * Goal 21. introclass.median.mid.median(III)I: Line 40
   * Goal 22. introclass.median.mid.median(III)I: Line 54
   * Goal 23. [METHOD] introclass.median.mid.<init>()V
   * Goal 24. [METHOD] introclass.median.mid.median(III)I
   * Goal 25. [METHODNOEX] introclass.median.mid.<init>()V
   * Goal 26. [METHODNOEX] introclass.median.mid.median(III)I
   * Goal 27. Weak Mutation 0: introclass.median.mid.median(III)I:20 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 1: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC 1
   * Goal 29. Weak Mutation 2: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC -1
   * Goal 30. Weak Mutation 3: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 4: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 32. Weak Mutation 5: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 33. Weak Mutation 6: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 34. Weak Mutation 7: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 35. Weak Mutation 8: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 36. Weak Mutation 9: introclass.median.mid.median(III)I:33 - ReplaceComparisonOperator <= -> -1
   * Goal 37. Weak Mutation 12: introclass.median.mid.median(III)I:34 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 13: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC 1
   * Goal 39. Weak Mutation 14: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC -1
   * Goal 40. Weak Mutation 15: introclass.median.mid.median(III)I:34 - InsertUnaryOp Negation
   * Goal 41. Weak Mutation 16: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC 1
   * Goal 42. Weak Mutation 17: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC -1
   * Goal 43. Weak Mutation 20: introclass.median.mid.median(III)I:34 - ReplaceComparisonOperator <= -> ==
   * Goal 44. Weak Mutation 24: introclass.median.mid.median(III)I:36 - InsertUnaryOp Negation
   * Goal 45. Weak Mutation 25: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC 1
   * Goal 46. Weak Mutation 26: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC -1
   * Goal 47. Weak Mutation 27: introclass.median.mid.median(III)I:36 - InsertUnaryOp Negation
   * Goal 48. Weak Mutation 28: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC 1
   * Goal 49. Weak Mutation 29: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC -1
   * Goal 50. Weak Mutation 30: introclass.median.mid.median(III)I:36 - ReplaceComparisonOperator > -> !=
   * Goal 51. Weak Mutation 33: introclass.median.mid.median(III)I:37 - InsertUnaryOp Negation
   * Goal 52. Weak Mutation 34: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC 1
   * Goal 53. Weak Mutation 35: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC -1
   * Goal 54. Weak Mutation 36: introclass.median.mid.median(III)I:37 - InsertUnaryOp Negation
   * Goal 55. Weak Mutation 37: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC 1
   * Goal 56. Weak Mutation 38: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC -1
   * Goal 57. Weak Mutation 40: introclass.median.mid.median(III)I:37 - ReplaceComparisonOperator <= -> <
   * Goal 58. Weak Mutation 45: introclass.median.mid.median(III)I:39 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 46: introclass.median.mid.median(III)I:39 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 47: introclass.median.mid.median(III)I:39 - InsertUnaryOp IINC -1
   * Goal 61. Weak Mutation 48: introclass.median.mid.median(III)I:39 - InsertUnaryOp Negation
   * Goal 62. Weak Mutation 49: introclass.median.mid.median(III)I:39 - InsertUnaryOp IINC 1
   * Goal 63. Weak Mutation 50: introclass.median.mid.median(III)I:39 - InsertUnaryOp IINC -1
   * Goal 64. Weak Mutation 53: introclass.median.mid.median(III)I:39 - ReplaceComparisonOperator > -> >=
   * Goal 65. Weak Mutation 54: introclass.median.mid.median(III)I:40 - InsertUnaryOp Negation
   * Goal 66. Weak Mutation 55: introclass.median.mid.median(III)I:40 - InsertUnaryOp IINC 1
   * Goal 67. Weak Mutation 56: introclass.median.mid.median(III)I:40 - InsertUnaryOp IINC -1
   * Goal 68. Weak Mutation 111: introclass.median.mid.median(III)I:54 - InsertUnaryOp Negation
   * Goal 69. Weak Mutation 112: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC 1
   * Goal 70. Weak Mutation 113: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC -1
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      mid mid0 = new mid();
      int int0 = mid0.median(812, (-646), 812);
      assertEquals(812, int0);
  }

  //Test case number: 6
  /*
   * 40 covered goals:
   * Goal 1. introclass.median.mid.<init>()V: root-Branch
   * Goal 2. introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - false
   * Goal 3. introclass.median.mid.median(III)I: I13 Branch 2 IF_ICMPLE L34 - false
   * Goal 4. Branch introclass.median.mid.<init>()V: root-Branch in context: introclass.median.mid:<init>()V
   * Goal 5. Branch introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - false in context: introclass.median.mid:median(III)I
   * Goal 6. Branch introclass.median.mid.median(III)I: I13 Branch 2 IF_ICMPLE L34 - false in context: introclass.median.mid:median(III)I
   * Goal 7. [Output]: introclass.median.mid.median(III)I:Positive
   * Goal 8. introclass.median.mid.<init>()V: Line 6
   * Goal 9. introclass.median.mid.median(III)I: Line 20
   * Goal 10. introclass.median.mid.median(III)I: Line 33
   * Goal 11. introclass.median.mid.median(III)I: Line 34
   * Goal 12. introclass.median.mid.median(III)I: Line 35
   * Goal 13. introclass.median.mid.median(III)I: Line 54
   * Goal 14. [METHOD] introclass.median.mid.<init>()V
   * Goal 15. [METHOD] introclass.median.mid.median(III)I
   * Goal 16. [METHODNOEX] introclass.median.mid.<init>()V
   * Goal 17. [METHODNOEX] introclass.median.mid.median(III)I
   * Goal 18. Weak Mutation 0: introclass.median.mid.median(III)I:20 - InsertUnaryOp Negation
   * Goal 19. Weak Mutation 1: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC 1
   * Goal 20. Weak Mutation 2: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC -1
   * Goal 21. Weak Mutation 3: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 22. Weak Mutation 4: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 23. Weak Mutation 5: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 24. Weak Mutation 6: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 25. Weak Mutation 7: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 26. Weak Mutation 8: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 27. Weak Mutation 9: introclass.median.mid.median(III)I:33 - ReplaceComparisonOperator <= -> -1
   * Goal 28. Weak Mutation 12: introclass.median.mid.median(III)I:34 - InsertUnaryOp Negation
   * Goal 29. Weak Mutation 13: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC 1
   * Goal 30. Weak Mutation 14: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC -1
   * Goal 31. Weak Mutation 15: introclass.median.mid.median(III)I:34 - InsertUnaryOp Negation
   * Goal 32. Weak Mutation 16: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC 1
   * Goal 33. Weak Mutation 17: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC -1
   * Goal 34. Weak Mutation 18: introclass.median.mid.median(III)I:34 - ReplaceComparisonOperator <= -> -1
   * Goal 35. Weak Mutation 21: introclass.median.mid.median(III)I:35 - InsertUnaryOp Negation
   * Goal 36. Weak Mutation 22: introclass.median.mid.median(III)I:35 - InsertUnaryOp IINC 1
   * Goal 37. Weak Mutation 23: introclass.median.mid.median(III)I:35 - InsertUnaryOp IINC -1
   * Goal 38. Weak Mutation 111: introclass.median.mid.median(III)I:54 - InsertUnaryOp Negation
   * Goal 39. Weak Mutation 112: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC 1
   * Goal 40. Weak Mutation 113: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC -1
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      mid mid0 = new mid();
      int int0 = mid0.median(812, 1, (-646));
      assertEquals(1, int0);
  }

  //Test case number: 7
  /*
   * 60 covered goals:
   * Goal 1. introclass.median.mid.<init>()V: root-Branch
   * Goal 2. introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - false
   * Goal 3. introclass.median.mid.median(III)I: I13 Branch 2 IF_ICMPLE L34 - true
   * Goal 4. introclass.median.mid.median(III)I: I23 Branch 3 IF_ICMPGT L36 - false
   * Goal 5. introclass.median.mid.median(III)I: I28 Branch 4 IF_ICMPLE L37 - false
   * Goal 6. Branch introclass.median.mid.<init>()V: root-Branch in context: introclass.median.mid:<init>()V
   * Goal 7. Branch introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - false in context: introclass.median.mid:median(III)I
   * Goal 8. Branch introclass.median.mid.median(III)I: I13 Branch 2 IF_ICMPLE L34 - true in context: introclass.median.mid:median(III)I
   * Goal 9. Branch introclass.median.mid.median(III)I: I23 Branch 3 IF_ICMPGT L36 - false in context: introclass.median.mid:median(III)I
   * Goal 10. Branch introclass.median.mid.median(III)I: I28 Branch 4 IF_ICMPLE L37 - false in context: introclass.median.mid:median(III)I
   * Goal 11. [Output]: introclass.median.mid.median(III)I:Zero
   * Goal 12. introclass.median.mid.<init>()V: Line 6
   * Goal 13. introclass.median.mid.median(III)I: Line 20
   * Goal 14. introclass.median.mid.median(III)I: Line 33
   * Goal 15. introclass.median.mid.median(III)I: Line 34
   * Goal 16. introclass.median.mid.median(III)I: Line 36
   * Goal 17. introclass.median.mid.median(III)I: Line 37
   * Goal 18. introclass.median.mid.median(III)I: Line 38
   * Goal 19. introclass.median.mid.median(III)I: Line 54
   * Goal 20. [METHOD] introclass.median.mid.<init>()V
   * Goal 21. [METHOD] introclass.median.mid.median(III)I
   * Goal 22. [METHODNOEX] introclass.median.mid.<init>()V
   * Goal 23. [METHODNOEX] introclass.median.mid.median(III)I
   * Goal 24. Weak Mutation 0: introclass.median.mid.median(III)I:20 - InsertUnaryOp Negation
   * Goal 25. Weak Mutation 1: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC 1
   * Goal 26. Weak Mutation 2: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC -1
   * Goal 27. Weak Mutation 3: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 4: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 29. Weak Mutation 5: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 30. Weak Mutation 6: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 7: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 32. Weak Mutation 8: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 33. Weak Mutation 9: introclass.median.mid.median(III)I:33 - ReplaceComparisonOperator <= -> -1
   * Goal 34. Weak Mutation 12: introclass.median.mid.median(III)I:34 - InsertUnaryOp Negation
   * Goal 35. Weak Mutation 13: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC 1
   * Goal 36. Weak Mutation 14: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC -1
   * Goal 37. Weak Mutation 15: introclass.median.mid.median(III)I:34 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 16: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC 1
   * Goal 39. Weak Mutation 17: introclass.median.mid.median(III)I:34 - InsertUnaryOp IINC -1
   * Goal 40. Weak Mutation 19: introclass.median.mid.median(III)I:34 - ReplaceComparisonOperator <= -> <
   * Goal 41. Weak Mutation 24: introclass.median.mid.median(III)I:36 - InsertUnaryOp Negation
   * Goal 42. Weak Mutation 25: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC 1
   * Goal 43. Weak Mutation 26: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC -1
   * Goal 44. Weak Mutation 27: introclass.median.mid.median(III)I:36 - InsertUnaryOp Negation
   * Goal 45. Weak Mutation 28: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC 1
   * Goal 46. Weak Mutation 29: introclass.median.mid.median(III)I:36 - InsertUnaryOp IINC -1
   * Goal 47. Weak Mutation 32: introclass.median.mid.median(III)I:36 - ReplaceComparisonOperator > -> >=
   * Goal 48. Weak Mutation 33: introclass.median.mid.median(III)I:37 - InsertUnaryOp Negation
   * Goal 49. Weak Mutation 34: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC 1
   * Goal 50. Weak Mutation 35: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC -1
   * Goal 51. Weak Mutation 36: introclass.median.mid.median(III)I:37 - InsertUnaryOp Negation
   * Goal 52. Weak Mutation 37: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC 1
   * Goal 53. Weak Mutation 38: introclass.median.mid.median(III)I:37 - InsertUnaryOp IINC -1
   * Goal 54. Weak Mutation 39: introclass.median.mid.median(III)I:37 - ReplaceComparisonOperator <= -> -1
   * Goal 55. Weak Mutation 42: introclass.median.mid.median(III)I:38 - InsertUnaryOp Negation
   * Goal 56. Weak Mutation 43: introclass.median.mid.median(III)I:38 - InsertUnaryOp IINC 1
   * Goal 57. Weak Mutation 44: introclass.median.mid.median(III)I:38 - InsertUnaryOp IINC -1
   * Goal 58. Weak Mutation 111: introclass.median.mid.median(III)I:54 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 112: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 113: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC -1
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      mid mid0 = new mid();
      int int0 = mid0.median(699, 0, 0);
      assertEquals(0, int0);
  }

  //Test case number: 8
  /*
   * 70 covered goals:
   * Goal 1. introclass.median.mid.<init>()V: root-Branch
   * Goal 2. introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true
   * Goal 3. introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false
   * Goal 4. introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - false
   * Goal 5. introclass.median.mid.median(III)I: I58 Branch 8 IF_ICMPLE L45 - true
   * Goal 6. introclass.median.mid.median(III)I: I68 Branch 9 IF_ICMPGT L47 - false
   * Goal 7. Branch introclass.median.mid.<init>()V: root-Branch in context: introclass.median.mid:<init>()V
   * Goal 8. Branch introclass.median.mid.median(III)I: I8 Branch 1 IF_ICMPLE L33 - true in context: introclass.median.mid:median(III)I
   * Goal 9. Branch introclass.median.mid.median(III)I: I48 Branch 6 IF_ICMPGT L43 - false in context: introclass.median.mid:median(III)I
   * Goal 10. Branch introclass.median.mid.median(III)I: I53 Branch 7 IF_ICMPLE L44 - false in context: introclass.median.mid:median(III)I
   * Goal 11. Branch introclass.median.mid.median(III)I: I58 Branch 8 IF_ICMPLE L45 - true in context: introclass.median.mid:median(III)I
   * Goal 12. Branch introclass.median.mid.median(III)I: I68 Branch 9 IF_ICMPGT L47 - false in context: introclass.median.mid:median(III)I
   * Goal 13. [Output]: introclass.median.mid.median(III)I:Negative
   * Goal 14. introclass.median.mid.<init>()V: Line 6
   * Goal 15. introclass.median.mid.median(III)I: Line 20
   * Goal 16. introclass.median.mid.median(III)I: Line 33
   * Goal 17. introclass.median.mid.median(III)I: Line 43
   * Goal 18. introclass.median.mid.median(III)I: Line 44
   * Goal 19. introclass.median.mid.median(III)I: Line 45
   * Goal 20. introclass.median.mid.median(III)I: Line 47
   * Goal 21. introclass.median.mid.median(III)I: Line 48
   * Goal 22. introclass.median.mid.median(III)I: Line 54
   * Goal 23. [METHOD] introclass.median.mid.<init>()V
   * Goal 24. [METHOD] introclass.median.mid.median(III)I
   * Goal 25. [METHODNOEX] introclass.median.mid.<init>()V
   * Goal 26. [METHODNOEX] introclass.median.mid.median(III)I
   * Goal 27. Weak Mutation 0: introclass.median.mid.median(III)I:20 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 1: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC 1
   * Goal 29. Weak Mutation 2: introclass.median.mid.median(III)I:20 - InsertUnaryOp IINC -1
   * Goal 30. Weak Mutation 3: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 4: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 32. Weak Mutation 5: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 33. Weak Mutation 6: introclass.median.mid.median(III)I:33 - InsertUnaryOp Negation
   * Goal 34. Weak Mutation 7: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC 1
   * Goal 35. Weak Mutation 8: introclass.median.mid.median(III)I:33 - InsertUnaryOp IINC -1
   * Goal 36. Weak Mutation 11: introclass.median.mid.median(III)I:33 - ReplaceComparisonOperator <= -> ==
   * Goal 37. Weak Mutation 57: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 58: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 39. Weak Mutation 59: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 40. Weak Mutation 60: introclass.median.mid.median(III)I:43 - InsertUnaryOp Negation
   * Goal 41. Weak Mutation 61: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC 1
   * Goal 42. Weak Mutation 62: introclass.median.mid.median(III)I:43 - InsertUnaryOp IINC -1
   * Goal 43. Weak Mutation 63: introclass.median.mid.median(III)I:43 - ReplaceComparisonOperator > -> !=
   * Goal 44. Weak Mutation 66: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 45. Weak Mutation 67: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 46. Weak Mutation 68: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 47. Weak Mutation 69: introclass.median.mid.median(III)I:44 - InsertUnaryOp Negation
   * Goal 48. Weak Mutation 70: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC 1
   * Goal 49. Weak Mutation 71: introclass.median.mid.median(III)I:44 - InsertUnaryOp IINC -1
   * Goal 50. Weak Mutation 72: introclass.median.mid.median(III)I:44 - ReplaceComparisonOperator <= -> -1
   * Goal 51. Weak Mutation 75: introclass.median.mid.median(III)I:45 - InsertUnaryOp Negation
   * Goal 52. Weak Mutation 76: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC 1
   * Goal 53. Weak Mutation 77: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC -1
   * Goal 54. Weak Mutation 78: introclass.median.mid.median(III)I:45 - InsertUnaryOp Negation
   * Goal 55. Weak Mutation 79: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC 1
   * Goal 56. Weak Mutation 80: introclass.median.mid.median(III)I:45 - InsertUnaryOp IINC -1
   * Goal 57. Weak Mutation 83: introclass.median.mid.median(III)I:45 - ReplaceComparisonOperator <= -> ==
   * Goal 58. Weak Mutation 87: introclass.median.mid.median(III)I:47 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 88: introclass.median.mid.median(III)I:47 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 89: introclass.median.mid.median(III)I:47 - InsertUnaryOp IINC -1
   * Goal 61. Weak Mutation 90: introclass.median.mid.median(III)I:47 - InsertUnaryOp Negation
   * Goal 62. Weak Mutation 91: introclass.median.mid.median(III)I:47 - InsertUnaryOp IINC 1
   * Goal 63. Weak Mutation 92: introclass.median.mid.median(III)I:47 - InsertUnaryOp IINC -1
   * Goal 64. Weak Mutation 93: introclass.median.mid.median(III)I:47 - ReplaceComparisonOperator > -> !=
   * Goal 65. Weak Mutation 96: introclass.median.mid.median(III)I:48 - InsertUnaryOp Negation
   * Goal 66. Weak Mutation 97: introclass.median.mid.median(III)I:48 - InsertUnaryOp IINC 1
   * Goal 67. Weak Mutation 98: introclass.median.mid.median(III)I:48 - InsertUnaryOp IINC -1
   * Goal 68. Weak Mutation 111: introclass.median.mid.median(III)I:54 - InsertUnaryOp Negation
   * Goal 69. Weak Mutation 112: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC 1
   * Goal 70. Weak Mutation 113: introclass.median.mid.median(III)I:54 - InsertUnaryOp IINC -1
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      mid mid0 = new mid();
      int int0 = mid0.median((-2288), 0, (-863));
      assertEquals((-863), int0);
  }
}
